main.js

this api generates random anime quotes
<hr>
Checklist

anime-quote-api

---

main.js

Displays the picture of random mouth watering food dishes . Perfect way to pump our passion up for cooking .
<hr>
Checklist

added foodish api

---

main.js

This API gives us good Chuck Norris Jokes without even an API key.
<hr>
Checklist

Add Chuck Norris Jokes Api

---

index.html
main.js

This API will show some random fun facts.
<hr>
Checklist

Added Fun Facts API

---

main.js

This API will show some random dog image.
<hr>
Checklist

Random Dogs API

---

package-lock.json
static/main.js
yarn.lock

Included API, that will show random Car Images.
<hr>
Checklist

Added Random Cars image generator

---

static/main.js

I have added the TV MAZE API response. It gives you a lot of information and also you don't need an API Key.
<hr>
Checklist

Added TV Maze API

---

static/main.js

Signed-off-by: yash2002109 <yash2002109@gmail.com>
Please include the details of the API used in this PR.
<hr>
Checklist

Add anime image API support

---

static/main.js

Added Dev.to API ( *A Platform to Blog as a Developer* )
Optional
<hr>
Checklist

Added Dev.to API

---

static/main.js

The Imgflip API uses a RESTful JSON interface which gets an array of popular meme templates. Memes serve many purposes and functions, but at a fundamental level, they serve as an expression of people's opinions and emotions.
<hr>
Checklist

Added ImgFlip API (Random Meme Template Generator)

---

static/main.js

Added an API that gets random cat image/gif
<hr>
Checklist

Added RandomCat API support

---

static/main.js

An API that provides random coffee images.
<hr>
Checklist

Added Coffee API

---

static/main.js

Reverts ashutoshkrris/Random-APIs#20

Revert "Added Coffee API"

---

static/main.js

Added Breaking Bad API which doesn't require any API Key. It provides all sorts of breaking bad information like Quotes, characters, etc.
<hr>
Checklist

Add Breaking Bad Api

---

static/main.js

Added a Dictionary API which doesn't require an API Key and can give you all the knowledge about a particular word.
<hr>
Checklist

Add Dictionary Api

---

static/main.js

nekos.best API provides fast and fully SFW anime images and role-playing GIFs for developers to use.
<hr>
Checklist

Added nekos.best API

---

static/main.js

- Kanye.rest API generates random quotes by Kanye West.
> you can find the API url here: https://api.kanye.rest
<hr>
Checklist

add kanye.rest API

---

package-lock.json
static/main.js
yarn.lock

Added game of thrones quote random API for hacktoberfest
Optional
<hr>
Checklist

Added random game of thrones quote API

---

index.html
static/css/index.css
static/main.js

**Add loader #11**
The website doesn't really need a loader, since the fetch calls that are executed first are added in the website first, the ones that take time are added in the end, which by the user reaches the end of the webpage will be executed. (You can refresh the website again and again to see that the responses differ in order everytime). But however, adding a loader isn't a bad idea in itself. It's good to let the user know there are more APIs in the website than the ones they are viewing at the moment.
I have made a loader and I am toggling the visibility off it based on receiving successful response.
You would also have to change the readme too
`loading.style.display="block";
fetch("https://api.adviceslip.com/advice", {
method: "GET",
})
.then((res) => res.json()) …

add loader

---

static/main.js

Added [Pokeapi](https://pokeapi.co/).
Optional
<hr>
Checklist

Add pokeapi

---

static/main.js

Used TheCocktailDB API to generate a cocktail recipe including a list of ingredients used as well as a drink of the image.
<hr>
Checklist

added fetch to TheCocktailDB

---

static/main.js

API that returns a random image of a panda.
<hr>
Checklist

Added Panda API

---

static/main.js

Adding the [Password-Generator API](https://github.com/fawazsullia/password-generator/).
<hr>
Checklist

Add Password-Generator API

---

static/main.js

This API gives Dog Facts
[Source](https://dukengn.github.io/Dog-facts-API/)
Optional
<hr>
Checklist
To tick a box, replace `[ ]` with `[x]`. 
Sorry for last time, I believe this works.

Added Dog Quotes

---

static/main.js

Added global covid data cases API for hacktoberfest 2021
Optional
<hr>
Checklist

Add covid data global cases API

---

static/main.js

API that recommends random activities to do
<hr>
Checklist

Added Bored API

---

static/main.js

added random jokes api
<hr>
Checklist

added jokes api

---

README.md
static/main.js

This will provide the Top 5 MLB pitchers of the 2021 regular season as measured by ERA (Earned Run Average).
<hr>
Checklist

Added Top 5 MLB Pitchers API

---

README.md

Added further details on the API response text section of the instructions. I wasn't too familiar with this myself until looking at others' code. I thought it would be helpful for future contributors in a similar situation as me.
<hr>
Checklist

Added further details to README.md instructions on response text

---

static/main.js

It will display us the random wallpapers from the API.
N/A
<hr>
Checklist

Added random wallpaper API

---

package-lock.json
static/main.js
yarn.lock

The TAYLOR SWIFT API generates her quotes and lyrics.
<hr>
Checklist

added the TAYLOR SWIFT API
